security:
    encoders:
        FOS\UserBundle\Model\UserInterface:
            algorithm:           sha256
            encode_as_base64:    true
            iterations:          5000

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
    role_hierarchy:
            ROLE_ADMIN:       [ROLE_MANAGER]
    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                default_target_path: /client

            logout:
              path: /logout
              target: /login
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/new/manager$, role: ROLE_ADMIN }
        - { path: ^/user, role: ROLE_MANAGER }
        - { path: ^/, role: ROLE_USER }
